In [1]:
import os
import math
import pandas as pd
from dotenv import load_dotenv

# Explicitly providing path to '.env'
from pathlib import Path  # Python 3.6+ only
# Load .env variables
_ = load_dotenv(dotenv_path=f"{Path().resolve().parents[1]}/src/.env")

# with the new api
from importnb import imports
with imports("ipynb"):
    from utils import to_timestamp, df_data_sensors, missing_data, correlation_data, df_to_csv, df_from_csv

PM2.5: 35.9, AQI: 102
PM2.5: 35.9, Measure Level: MeasureLevels.UNHEALTHY_FOR_SENSITIVE_GROUPS, Range Values: Min: 35.5, Max: 55.4
AQI: 102, Measure Level: MeasureLevels.UNHEALTHY_FOR_SENSITIVE_GROUPS, Range Values: Min: 101, Max: 150

## Reference

In [2]:
# Load Tangara Reference
df_reference = df_from_csv("reference.csv", datafolder='2_features', dtindex=False)
print(f"Tangara Sensor Reference: {df_reference['ID'].values[0]}")

df_reference

2024-07-15 18:49:21.725 | DEBUG    | utils:df_from_csv:340 - Load DataFrame: /home/sebaxtian/Workspaces/Tangara/tangara-evaluation/src/data/2_features/reference.csv

Tangara Sensor Reference: TANGARA_25BE

,ID,GEOHASH,MAC,GEOLOCATION,LATITUDE,LONGITUDE
0,TANGARA_25BE,d29e6de,D29ESP32DE725BE,3.3982086181640625 -76.52595520019531,3.398209,-76.525955

## Targets

In [3]:
# Load Tangara Targets
df_targets = df_from_csv("targets.csv", datafolder='2_features', dtindex=False)
print(f"Total Tangara Sensor Targets: {len(df_targets)}")

df_targets

2024-07-15 18:49:21.754 | DEBUG    | utils:df_from_csv:340 - Load DataFrame: /home/sebaxtian/Workspaces/Tangara/tangara-evaluation/src/data/2_features/targets.csv

Total Tangara Sensor Targets: 23

,ID,GEOHASH,MAC,GEOLOCATION,LATITUDE,LONGITUDE
0,TANGARA_B7BE,d29e6de,D29ESP32DE0B7BE,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
1,TANGARA_C752,d29e6de,D29ESP32DE0C752,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
2,TANGARA_A682,d29e6d7,D29ESP32DE3A682,3.3968353271484375 -76.52595520019531,3.396835,-76.525955
3,TANGARA_ADD6,d29e6de,D29ESP32DE3ADD6,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
4,TANGARA_B08A,d29e6de,D29ESP32DE3B08A,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
5,TANGARA_B9CA,d29e6de,D29ESP32DE3B9CA,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
6,TANGARA_BC5A,d29e6ds,D29ESP32DE3BC5A,3.3982086181640625 -76.52458190917969,3.398209,-76.524582
7,TANGARA_BCC6,d29e6de,D29ESP32DE3BCC6,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
8,TANGARA_BD5E,d29e6de,D29ESP32DE3BD5E,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
9,TANGARA_BE12,d29e6de,D29ESP32DE3BE12,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
10,TANGARA_79CA,d29e6de,D29ESP32DE679CA,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
11,TANGARA_0E26,d29e6de,D29ESP32DE70E26,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
12,TANGARA_1402,d29e6de,D29ESP32DE71402,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
13,TANGARA_157E,d29e6de,D29ESP32DE7157E,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
14,TANGARA_18DA,d29e6de,D29ESP32DE718DA,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
15,TANGARA_1DE2,d29e6de,D29ESP32DE71DE2,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
16,TANGARA_211E,d29e6de,D29ESP32DE7211E,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
17,TANGARA_25F2,d29e6de,D29ESP32DE725F2,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
18,TANGARA_298A,d29e6de,D29ESP32DE7298A,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
19,TANGARA_3376,d29e6de,D29ESP32DE73376,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
20,TANGARA_A43A,d29e6ds,D29ESP32DEFA43A,3.3982086181640625 -76.52458190917969,3.398209,-76.524582
21,TANGARA_C17E,d29e6de,D29ESP32DEFC17E,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
22,TANGARA_CA62,d29e6de,D29ESP32DEFCA62,3.3982086181640625 -76.52595520019531,3.398209,-76.525955

## Tangaras

In [4]:
# Tangaras from Reference and Targets
df_tangaras = pd.concat([df_reference, df_targets], ignore_index=True)
print(f"Total Tangara Sensors: {len(df_tangaras)}")

df_tangaras

Total Tangara Sensors: 24

,ID,GEOHASH,MAC,GEOLOCATION,LATITUDE,LONGITUDE
0,TANGARA_25BE,d29e6de,D29ESP32DE725BE,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
1,TANGARA_B7BE,d29e6de,D29ESP32DE0B7BE,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
2,TANGARA_C752,d29e6de,D29ESP32DE0C752,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
3,TANGARA_A682,d29e6d7,D29ESP32DE3A682,3.3968353271484375 -76.52595520019531,3.396835,-76.525955
4,TANGARA_ADD6,d29e6de,D29ESP32DE3ADD6,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
5,TANGARA_B08A,d29e6de,D29ESP32DE3B08A,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
6,TANGARA_B9CA,d29e6de,D29ESP32DE3B9CA,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
7,TANGARA_BC5A,d29e6ds,D29ESP32DE3BC5A,3.3982086181640625 -76.52458190917969,3.398209,-76.524582
8,TANGARA_BCC6,d29e6de,D29ESP32DE3BCC6,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
9,TANGARA_BD5E,d29e6de,D29ESP32DE3BD5E,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
10,TANGARA_BE12,d29e6de,D29ESP32DE3BE12,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
11,TANGARA_79CA,d29e6de,D29ESP32DE679CA,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
12,TANGARA_0E26,d29e6de,D29ESP32DE70E26,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
13,TANGARA_1402,d29e6de,D29ESP32DE71402,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
14,TANGARA_157E,d29e6de,D29ESP32DE7157E,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
15,TANGARA_18DA,d29e6de,D29ESP32DE718DA,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
16,TANGARA_1DE2,d29e6de,D29ESP32DE71DE2,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
17,TANGARA_211E,d29e6de,D29ESP32DE7211E,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
18,TANGARA_25F2,d29e6de,D29ESP32DE725F2,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
19,TANGARA_298A,d29e6de,D29ESP32DE7298A,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
20,TANGARA_3376,d29e6de,D29ESP32DE73376,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
21,TANGARA_A43A,d29e6ds,D29ESP32DEFA43A,3.3982086181640625 -76.52458190917969,3.398209,-76.524582
22,TANGARA_C17E,d29e6de,D29ESP32DEFC17E,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
23,TANGARA_CA62,d29e6de,D29ESP32DEFCA62,3.3982086181640625 -76.52595520019531,3.398209,-76.525955

## Humidity Raw Data

In [5]:
# Start Date Time ISO 8601 Format, TZ='America/Bogota' -05:00
START_ISO8601_DATETIME = os.getenv("START_ISO8601_DATETIME", None)
start_timestamp = to_timestamp(START_ISO8601_DATETIME)
# End Date Time ISO 8601 Format, TZ='America/Bogota' -05:00
END_ISO8601_DATETIME = os.getenv("END_ISO8601_DATETIME", None)
end_timestamp = to_timestamp(os.getenv("END_ISO8601_DATETIME", None))

# GROUP BY TIME
GROUP_BY_TIME = os.getenv("GROUP_BY_TIME", None)

print(f'Since: {START_ISO8601_DATETIME} -> {start_timestamp}, Until: {END_ISO8601_DATETIME} -> {end_timestamp}')
print(f"Group by Time: {GROUP_BY_TIME}")

2024-07-15 18:49:21.804 | DEBUG    | utils:to_timestamp:99 - datetime_iso8601: 2024-07-15T19:49:00-05:00, Timestamp: 1721090940000
2024-07-15 18:49:21.806 | DEBUG    | utils:to_timestamp:99 - datetime_iso8601: 2024-07-15T20:49:00-05:00, Timestamp: 1721094540000

Since: 2024-07-15T19:49:00-05:00 -> 1721090940000, Until: 2024-07-15T20:49:00-05:00 -> 1721094540000
Group by Time: 30s

In [6]:
# Humidity Data Frame Sensors
df_hum_raw = df_data_sensors(df_tangaras, start_timestamp, end_timestamp, 'hum', GROUP_BY_TIME)
df_hum_raw
#df_hum_raw.shape

2024-07-15 18:49:21.816 | DEBUG    | utils:query_measure:192 - sql_query: SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE725BE') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE0B7BE') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE0C752') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE3A682') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE3ADD6') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE3B08A') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE3B9CA') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE3BC5A') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE3BCC6') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE3BD5E') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE3BE12') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE679CA') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE70E26') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE71402') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE7157E') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE718DA') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE71DE2') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE7211E') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE725F2') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE7298A') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE73376') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DEFA43A') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DEFC17E') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DEFCA62') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null)
2024-07-15 18:49:22.218 | DEBUG    | utils:request_influxdb:131 - response: <Response [200]>
2024-07-15 18:49:22.303 | DEBUG    | utils:df_data_sensors:480 - Measure Data Frame Sensors: <class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 121 entries, 2024-07-15 19:49:00-05:00 to 2024-07-15 20:49:00-05:00
Freq: 30S
Data columns (total 24 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   TANGARA_25BE  110 non-null    float64
 1   TANGARA_B7BE  81 non-null     float64
 2   TANGARA_C752  88 non-null     float64
 3   TANGARA_A682  118 non-null    float64
 4   TANGARA_ADD6  120 non-null    float64
 5   TANGARA_B08A  111 non-null    float64
 6   TANGARA_B9CA  120 non-null    float64
 7   TANGARA_BC5A  117 non-null    float64
 8   TANGARA_BCC6  113 non-null    float64
 9   TANGARA_BD5E  113 non-null    float64
 10  TANGARA_BE12  108 non-null    float64
 11  TANGARA_79CA  120 non-null    float64
 12  TANGARA_0E26  115 non-null    float64
 13  TANGARA_1402  120 non-null    float64
 14  TANGARA_157E  109 non-null    float64
 15  TANGARA_18DA  120 non-null    float64
 16  TANGARA_1DE2  120 non-null    float64
 17  TANGARA_211E  120 non-null    float64
 18  TANGARA_25F2  117 non-null    float64
 19  TANGARA_298A  109 non-null    float64
 20  TANGARA_3376  115 non-null    float64
 21  TANGARA_A43A  120 non-null    float64
 22  TANGARA_C17E  120 non-null    float64
 23  TANGARA_CA62  120 non-null    float64
dtypes: float64(24)
memory usage: 23.6 KB

,TANGARA_25BE,TANGARA_B7BE,TANGARA_C752,TANGARA_A682,TANGARA_ADD6,TANGARA_B08A,TANGARA_B9CA,TANGARA_BC5A,TANGARA_BCC6,TANGARA_BD5E,...,TANGARA_157E,TANGARA_18DA,TANGARA_1DE2,TANGARA_211E,TANGARA_25F2,TANGARA_298A,TANGARA_3376,TANGARA_A43A,TANGARA_C17E,TANGARA_CA62
DATETIME,,,,,,,,,,,,,,,,,,,,,
2024-07-15 19:49:00-05:00,48.13,NaN,57.41,41.86,44.20,44.01,40.85,42.47,37.24,44.74,...,43.32,50.00,40.10,43.70,50.79,40.01,46.20,42.33,40.57,47.15
2024-07-15 19:49:30-05:00,NaN,45.40,57.41,41.87,44.21,43.99,40.85,42.53,37.55,44.79,...,43.30,50.01,40.06,43.73,51.63,NaN,46.16,42.36,40.61,47.13
2024-07-15 19:50:00-05:00,48.98,45.67,57.41,41.76,44.24,44.01,40.86,42.80,37.66,44.78,...,43.26,50.03,40.09,43.90,51.11,39.97,46.16,42.41,40.91,47.10
2024-07-15 19:50:30-05:00,49.44,46.08,57.41,41.72,44.21,44.09,40.85,42.95,38.24,44.78,...,43.26,49.96,40.13,44.03,52.11,40.00,46.20,42.42,41.13,47.12
2024-07-15 19:51:00-05:00,48.84,NaN,57.41,41.89,44.25,44.17,40.85,43.13,37.45,44.79,...,43.31,50.02,40.14,44.11,51.13,40.13,46.19,42.46,41.15,47.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-07-15 20:47:00-05:00,47.50,NaN,NaN,40.92,44.16,43.24,40.30,41.78,37.00,44.60,...,42.25,49.07,39.74,42.44,50.05,39.06,46.35,41.84,39.29,46.35
2024-07-15 20:47:30-05:00,47.15,44.67,NaN,40.80,44.13,43.13,40.30,41.74,36.77,44.59,...,42.22,49.07,39.69,42.45,49.74,38.98,46.36,41.85,39.32,46.40
2024-07-15 20:48:00-05:00,47.35,NaN,NaN,40.85,44.11,43.20,40.29,41.76,36.97,44.59,...,NaN,49.05,39.70,42.45,49.88,NaN,46.35,41.83,39.34,46.39
2024-07-15 20:48:30-05:00,47.32,NaN,NaN,40.83,44.16,43.17,40.26,41.68,36.85,44.53,...,42.19,49.02,39.70,42.50,49.88,NaN,46.34,41.87,39.30,46.40
2024-07-15 20:49:00-05:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Descriptive Statistics

In [7]:
# Describe Data
df_hum_raw.describe()

,TANGARA_25BE,TANGARA_B7BE,TANGARA_C752,TANGARA_A682,TANGARA_ADD6,TANGARA_B08A,TANGARA_B9CA,TANGARA_BC5A,TANGARA_BCC6,TANGARA_BD5E,...,TANGARA_157E,TANGARA_18DA,TANGARA_1DE2,TANGARA_211E,TANGARA_25F2,TANGARA_298A,TANGARA_3376,TANGARA_A43A,TANGARA_C17E,TANGARA_CA62
count,110.000000,81.000000,8.800000e+01,118.000000,120.000000,111.000000,120.000000,117.000000,113.000000,113.000000,...,109.000000,120.000000,120.000000,120.000000,117.000000,109.000000,115.000000,120.000000,120.000000,120.000000
mean,47.865818,45.044074,5.741000e+01,41.324831,44.289833,43.583423,40.630083,42.154274,37.098584,44.749204,...,42.753028,49.594167,39.974917,43.185750,50.515214,39.513211,46.334783,42.091167,40.092250,46.693750
std,0.582083,0.391886,2.143844e-14,0.386487,0.068477,0.304086,0.201046,0.370980,0.350015,0.093772,...,0.435400,0.342481,0.149352,0.492721,0.591158,0.354617,0.069337,0.220165,0.488695,0.286448
min,46.970000,44.230000,5.741000e+01,40.780000,44.110000,43.130000,40.260000,41.470000,36.150000,44.530000,...,41.990000,49.020000,39.690000,42.440000,49.520000,38.950000,46.160000,41.780000,39.290000,46.240000
25%,47.355000,44.780000,5.741000e+01,40.952500,44.250000,43.310000,40.417500,41.860000,36.830000,44.660000,...,42.390000,49.247500,39.820000,42.705000,50.020000,39.200000,46.300000,41.890000,39.687500,46.397500
50%,47.840000,45.100000,5.741000e+01,41.245000,44.310000,43.490000,40.620000,42.120000,37.070000,44.780000,...,42.710000,49.605000,40.000000,43.155000,50.450000,39.450000,46.360000,42.025000,40.000000,46.670000
75%,48.277500,45.290000,5.741000e+01,41.757500,44.340000,43.850000,40.820000,42.460000,37.390000,44.830000,...,43.220000,49.927500,40.110000,43.652500,50.990000,39.840000,46.385000,42.300000,40.520000,46.962500
max,49.440000,46.080000,5.741000e+01,42.020000,44.390000,44.170000,40.920000,43.130000,38.240000,44.880000,...,43.470000,50.050000,40.180000,44.110000,52.110000,40.170000,46.420000,42.480000,41.150000,47.150000

## Missing Data

In [8]:
import warnings
warnings.filterwarnings('ignore')

# Missing Data Threshold
threshold_data = float(os.getenv("THRESHOLD_MISSING_DATA", None))
print(f'Threshold Missing Data: {int(threshold_data * 100)}%')

# DataFrame Report for Missing Data Humidity
df_hum_missing_data = pd.DataFrame({'ID': [], 'TO_BE_CHECKED': [], 'DATA_PERCENT': [], 'MISSING_DATA_PERCENT': [], 'THRESHOLD_MISSING_DATA': []})

# For each Tangara sensor
for id_tangara_sensor in df_hum_raw.columns:
    df_hum_sensor = df_hum_raw[[id_tangara_sensor]]
    # To be checked
    to_be_checked, data_percent, missing_data_percent = missing_data(df_hum_sensor, threshold_data)
    if to_be_checked:
        print(f"Tangara Sensor: {id_tangara_sensor}, To be checked: {to_be_checked}, Data: {data_percent}%, Missing Data: {missing_data_percent}%, Threshold: {threshold_data}%")
        # Drop Tangara Sensor from original dataframe
        # df_hum_raw = df_hum_raw.drop(id_tangara_sensor, axis=1)
    
    # Insert into DataFrame Report
    df_hum_missing_data.loc[len(df_hum_missing_data.index)] = [id_tangara_sensor, to_be_checked, data_percent, missing_data_percent, threshold_data]

df_hum_missing_data

2024-07-15 18:49:22.451 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_25BE, To be checked: False, Data: 91%, Missing Data: 9%, Threshold: 80%
2024-07-15 18:49:22.457 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_B7BE, To be checked: True, Data: 67%, Missing Data: 33%, Threshold: 80%
2024-07-15 18:49:22.462 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_C752, To be checked: True, Data: 73%, Missing Data: 27%, Threshold: 80%
2024-07-15 18:49:22.466 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_A682, To be checked: False, Data: 98%, Missing Data: 2%, Threshold: 80%
2024-07-15 18:49:22.472 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_ADD6, To be checked: False, Data: 99%, Missing Data: 1%, Threshold: 80%
2024-07-15 18:49:22.476 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_B08A, To be checked: False, Data: 92%, Missing Data: 8%, Threshold: 80%
2024-07-15 18:49:22.482 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_B9CA, To be checked: False, Data: 99%, Missing Data: 1%, Threshold: 80%
2024-07-15 18:49:22.486 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_BC5A, To be checked: False, Data: 97%, Missing Data: 3%, Threshold: 80%
2024-07-15 18:49:22.492 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_BCC6, To be checked: False, Data: 93%, Missing Data: 7%, Threshold: 80%
2024-07-15 18:49:22.496 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_BD5E, To be checked: False, Data: 93%, Missing Data: 7%, Threshold: 80%
2024-07-15 18:49:22.502 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_BE12, To be checked: False, Data: 89%, Missing Data: 11%, Threshold: 80%
2024-07-15 18:49:22.507 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_79CA, To be checked: False, Data: 99%, Missing Data: 1%, Threshold: 80%
2024-07-15 18:49:22.512 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_0E26, To be checked: False, Data: 95%, Missing Data: 5%, Threshold: 80%
2024-07-15 18:49:22.517 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_1402, To be checked: False, Data: 99%, Missing Data: 1%, Threshold: 80%
2024-07-15 18:49:22.522 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_157E, To be checked: False, Data: 90%, Missing Data: 10%, Threshold: 80%
2024-07-15 18:49:22.529 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_18DA, To be checked: False, Data: 99%, Missing Data: 1%, Threshold: 80%
2024-07-15 18:49:22.533 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_1DE2, To be checked: False, Data: 99%, Missing Data: 1%, Threshold: 80%
2024-07-15 18:49:22.538 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_211E, To be checked: False, Data: 99%, Missing Data: 1%, Threshold: 80%
2024-07-15 18:49:22.543 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_25F2, To be checked: False, Data: 97%, Missing Data: 3%, Threshold: 80%
2024-07-15 18:49:22.548 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_298A, To be checked: False, Data: 90%, Missing Data: 10%, Threshold: 80%
2024-07-15 18:49:22.553 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_3376, To be checked: False, Data: 95%, Missing Data: 5%, Threshold: 80%
2024-07-15 18:49:22.557 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_A43A, To be checked: False, Data: 99%, Missing Data: 1%, Threshold: 80%
2024-07-15 18:49:22.563 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_C17E, To be checked: False, Data: 99%, Missing Data: 1%, Threshold: 80%
2024-07-15 18:49:22.570 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_CA62, To be checked: False, Data: 99%, Missing Data: 1%, Threshold: 80%

Threshold Missing Data: 80%
Tangara Sensor: TANGARA_B7BE, To be checked: True, Data: 67%, Missing Data: 33%, Threshold: 0.8%
Tangara Sensor: TANGARA_C752, To be checked: True, Data: 73%, Missing Data: 27%, Threshold: 0.8%

,ID,TO_BE_CHECKED,DATA_PERCENT,MISSING_DATA_PERCENT,THRESHOLD_MISSING_DATA
0,TANGARA_25BE,False,91,9,0.8
1,TANGARA_B7BE,True,67,33,0.8
2,TANGARA_C752,True,73,27,0.8
3,TANGARA_A682,False,98,2,0.8
4,TANGARA_ADD6,False,99,1,0.8
5,TANGARA_B08A,False,92,8,0.8
6,TANGARA_B9CA,False,99,1,0.8
7,TANGARA_BC5A,False,97,3,0.8
8,TANGARA_BCC6,False,93,7,0.8
9,TANGARA_BD5E,False,93,7,0.8
10,TANGARA_BE12,False,89,11,0.8
11,TANGARA_79CA,False,99,1,0.8
12,TANGARA_0E26,False,95,5,0.8
13,TANGARA_1402,False,99,1,0.8
14,TANGARA_157E,False,90,10,0.8
15,TANGARA_18DA,False,99,1,0.8
16,TANGARA_1DE2,False,99,1,0.8
17,TANGARA_211E,False,99,1,0.8
18,TANGARA_25F2,False,97,3,0.8
19,TANGARA_298A,False,90,10,0.8
20,TANGARA_3376,False,95,5,0.8
21,TANGARA_A43A,False,99,1,0.8
22,TANGARA_C17E,False,99,1,0.8
23,TANGARA_CA62,False,99,1,0.8

In [9]:
# Save DataFrame Report for Missing Data Humidity into CSV file
df_hum_missing_data.set_index('ID', inplace=True)
df_to_csv(df_hum_missing_data, "hum_missing.csv", datafolder='2_features')

2024-07-15 18:49:22.601 | DEBUG    | utils:df_to_csv:311 - Save DataFrame: /home/sebaxtian/Workspaces/Tangara/tangara-evaluation/src/data/2_features/hum_missing.csv

## Data Correlation

In [10]:
# Data Correlation Threshold
threshold_correlation = float(os.getenv("THRESHOLD_CORRELATION_DATA", None))
print(f'Threshold Correlation Data: {int(threshold_correlation * 100)}%')

# Tangara Sensor Reference
ID_TANGARA_REFERENCE = df_reference['ID'].values[0]
df_hum_reference = df_hum_raw[[ID_TANGARA_REFERENCE]]

# DataFrame Report for Data Correlation Humidity
df_hum_correlation_data = pd.DataFrame({'ID_REFERENCE': [], 'ID_TARGET': [], 'THERE_IS_CORRELATION': [], 'CORRELATION_VALUE': [], 'THRESHOLD_CORRELATION': []})

# For each Tangara Sensor Target
for id_tangara_sensor in df_hum_raw.columns:
    if id_tangara_sensor != ID_TANGARA_REFERENCE:
        # Target Tangara Sensor
        df_hum_target = df_hum_raw[[id_tangara_sensor]]
        
        # To be checked
        if not math.isnan(df_hum_reference.std()):
            has_corr, corr = correlation_data(df_hum_reference, df_hum_target, threshold_correlation)
            if not has_corr:
                print(f"Tangara Sensor Reference: {ID_TANGARA_REFERENCE}, Tangara Sensors Target: {df_hum_target.columns[0]}, There is correlation: {has_corr}, Correlation: {float("{:.2f}".format(corr))}, Threshold: {threshold_correlation}")

                # Drop Tangara Sensor from original dataframe
                # df_hum_raw = df_hum_raw.drop(id_tangara, axis=1)
            
            # Insert into DataFrame Report
            df_hum_correlation_data.loc[len(df_hum_correlation_data.index)] = [ID_TANGARA_REFERENCE, df_hum_target.columns[0], has_corr, float("{:.2f}".format(corr)), threshold_correlation]

df_hum_correlation_data

2024-07-15 18:49:22.622 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_B7BE, There is correlation: False, Correlation: 0.76, Threshold: 0.8
2024-07-15 18:49:22.629 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_C752, There is correlation: False, Correlation: 0.0, Threshold: 0.8
2024-07-15 18:49:22.636 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_A682, There is correlation: True, Correlation: 0.81, Threshold: 0.8
2024-07-15 18:49:22.643 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_ADD6, There is correlation: False, Correlation: 0.08, Threshold: 0.8
2024-07-15 18:49:22.651 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_B08A, There is correlation: True, Correlation: 0.84, Threshold: 0.8
2024-07-15 18:49:22.657 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_B9CA, There is correlation: False, Correlation: 0.65, Threshold: 0.8

Threshold Correlation Data: 80%
Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_B7BE, There is correlation: False, Correlation: 0.76, Threshold: 0.8
Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_C752, There is correlation: False, Correlation: 0.0, Threshold: 0.8
Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_ADD6, There is correlation: False, Correlation: 0.08, Threshold: 0.8

2024-07-15 18:49:22.665 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_BC5A, There is correlation: True, Correlation: 0.92, Threshold: 0.8
2024-07-15 18:49:22.672 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_BCC6, There is correlation: True, Correlation: 0.87, Threshold: 0.8
2024-07-15 18:49:22.679 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_BD5E, There is correlation: False, Correlation: 0.42, Threshold: 0.8
2024-07-15 18:49:22.685 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_BE12, There is correlation: True, Correlation: 0.9, Threshold: 0.8
2024-07-15 18:49:22.693 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_79CA, There is correlation: False, Correlation: -0.7, Threshold: 0.8
2024-07-15 18:49:22.699 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_0E26, There is correlation: False, Correlation: 0.65, Threshold: 0.8
2024-07-15 18:49:22.708 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_1402, There is correlation: False, Correlation: 0.77, Threshold: 0.8
2024-07-15 18:49:22.715 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_157E, There is correlation: False, Correlation: 0.78, Threshold: 0.8
2024-07-15 18:49:22.721 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_18DA, There is correlation: False, Correlation: 0.63, Threshold: 0.8
2024-07-15 18:49:22.729 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_1DE2, There is correlation: False, Correlation: 0.59, Threshold: 0.8
2024-07-15 18:49:22.736 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_211E, There is correlation: True, Correlation: 0.82, Threshold: 0.8
2024-07-15 18:49:22.742 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_25F2, There is correlation: True, Correlation: 0.96, Threshold: 0.8
2024-07-15 18:49:22.749 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_298A, There is correlation: True, Correlation: 0.82, Threshold: 0.8
2024-07-15 18:49:22.756 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_3376, There is correlation: False, Correlation: -0.69, Threshold: 0.8
2024-07-15 18:49:22.764 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_A43A, There is correlation: True, Correlation: 0.81, Threshold: 0.8
2024-07-15 18:49:22.773 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_C17E, There is correlation: True, Correlation: 0.86, Threshold: 0.8
2024-07-15 18:49:22.779 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_CA62, There is correlation: False, Correlation: 0.7, Threshold: 0.8

Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_B9CA, There is correlation: False, Correlation: 0.65, Threshold: 0.8
Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_BD5E, There is correlation: False, Correlation: 0.42, Threshold: 0.8
Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_79CA, There is correlation: False, Correlation: -0.7, Threshold: 0.8
Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_0E26, There is correlation: False, Correlation: 0.65, Threshold: 0.8
Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_1402, There is correlation: False, Correlation: 0.77, Threshold: 0.8
Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_157E, There is correlation: False, Correlation: 0.78, Threshold: 0.8
Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_18DA, There is correlation: False, Correlation: 0.63, Threshold: 0.8
Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_1DE2, There is correlation: False, Correlation: 0.59, Threshold: 0.8
Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_3376, There is correlation: False, Correlation: -0.69, Threshold: 0.8
Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_CA62, There is correlation: False, Correlation: 0.7, Threshold: 0.8

,ID_REFERENCE,ID_TARGET,THERE_IS_CORRELATION,CORRELATION_VALUE,THRESHOLD_CORRELATION
0,TANGARA_25BE,TANGARA_B7BE,False,0.76,0.8
1,TANGARA_25BE,TANGARA_C752,False,0.00,0.8
2,TANGARA_25BE,TANGARA_A682,True,0.81,0.8
3,TANGARA_25BE,TANGARA_ADD6,False,0.08,0.8
4,TANGARA_25BE,TANGARA_B08A,True,0.84,0.8
5,TANGARA_25BE,TANGARA_B9CA,False,0.65,0.8
6,TANGARA_25BE,TANGARA_BC5A,True,0.92,0.8
7,TANGARA_25BE,TANGARA_BCC6,True,0.87,0.8
8,TANGARA_25BE,TANGARA_BD5E,False,0.42,0.8
9,TANGARA_25BE,TANGARA_BE12,True,0.90,0.8
10,TANGARA_25BE,TANGARA_79CA,False,-0.70,0.8
11,TANGARA_25BE,TANGARA_0E26,False,0.65,0.8
12,TANGARA_25BE,TANGARA_1402,False,0.77,0.8
13,TANGARA_25BE,TANGARA_157E,False,0.78,0.8
14,TANGARA_25BE,TANGARA_18DA,False,0.63,0.8
15,TANGARA_25BE,TANGARA_1DE2,False,0.59,0.8
16,TANGARA_25BE,TANGARA_211E,True,0.82,0.8
17,TANGARA_25BE,TANGARA_25F2,True,0.96,0.8
18,TANGARA_25BE,TANGARA_298A,True,0.82,0.8
19,TANGARA_25BE,TANGARA_3376,False,-0.69,0.8
20,TANGARA_25BE,TANGARA_A43A,True,0.81,0.8
21,TANGARA_25BE,TANGARA_C17E,True,0.86,0.8
22,TANGARA_25BE,TANGARA_CA62,False,0.70,0.8

In [11]:
# Save DataFrame Report for Data Correlation Humidity into CSV file
df_hum_correlation_data.set_index('ID_TARGET', inplace=True)
df_to_csv(df_hum_correlation_data, "hum_correlation.csv", datafolder='2_features')

2024-07-15 18:49:22.808 | DEBUG    | utils:df_to_csv:311 - Save DataFrame: /home/sebaxtian/Workspaces/Tangara/tangara-evaluation/src/data/2_features/hum_correlation.csv

In [12]:
# Save Humidity Data Frame Sensors into CSV file
df_to_csv(df_hum_raw, "hum_raw.csv")

2024-07-15 18:49:22.827 | DEBUG    | utils:df_to_csv:311 - Save DataFrame: /home/sebaxtian/Workspaces/Tangara/tangara-evaluation/src/data/0_raw/hum_raw.csv