In [1]:
import os
import math
from dotenv import load_dotenv

# Explicitly providing path to '.env'
from pathlib import Path  # Python 3.6+ only
# Load .env variables
_ = load_dotenv(dotenv_path=f"{Path().resolve().parents[1]}/src/.env")

# with the new api
from importnb import imports
with imports("ipynb"):
    from utils import df_from_csv, missing_data, correlation_data, plot_hist, plot_boxes, plot_lines, df_to_csv, drop_pm25_outliers

PM2.5: 35.9, AQI: 102
PM2.5: 35.9, Measure Level: MeasureLevels.UNHEALTHY_FOR_SENSITIVE_GROUPS, Range Values: Min: 35.5, Max: 55.4
AQI: 102, Measure Level: MeasureLevels.UNHEALTHY_FOR_SENSITIVE_GROUPS, Range Values: Min: 101, Max: 150

## PM2.5 Clean Data

In [2]:
# Load Raw Data
df_pm25_raw = df_from_csv("pm25_raw.csv")

# Check Data Types
print(df_pm25_raw.dtypes)

df_pm25_raw.head()

2024-03-01 17:19:40.540 | DEBUG    | utils:df_from_csv:340 - Load DataFrame: /home/sebaxtian/Workspaces/Tangara/tangara-evaluation/src/data/0_raw/pm25_raw.csv

TANGARA_3BEA    float64
TANGARA_421A    float64
TANGARA_422A    float64
TANGARA_5636    float64
TANGARA_D282    float64
dtype: object

,TANGARA_3BEA,TANGARA_421A,TANGARA_422A,TANGARA_5636,TANGARA_D282
DATETIME,,,,,
2023-12-30 00:00:00-05:00,NaN,NaN,NaN,NaN,NaN
2023-12-30 00:00:30-05:00,8.0,7.0,6.0,8.0,8.0
2023-12-30 00:01:00-05:00,7.0,8.0,7.0,7.0,8.0
2023-12-30 00:01:30-05:00,8.0,8.0,7.0,7.0,7.0
2023-12-30 00:02:00-05:00,8.0,7.0,7.0,7.0,7.0

## Descriptive Statistics

In [3]:
# Describe Data
df_pm25_raw.describe()

       TANGARA_3BEA  TANGARA_421A  TANGARA_422A  TANGARA_5636  TANGARA_D282
count  23274.000000  20774.000000  20796.000000  22104.000000  22245.000000
mean       7.956475      7.407336      7.466436      7.863147      9.167049
std       50.581405     45.621187     45.306838     65.148359     94.734987
min        1.000000      1.000000      1.000000      1.000000      1.000000
25%        4.000000      4.000000      4.000000      4.000000      5.000000
50%        6.000000      6.000000      6.000000      6.000000      7.000000
75%        9.000000      8.000000      8.000000      8.000000     10.000000
max     6030.000000   5959.000000   4917.000000   8154.000000  13475.000000

## Missing Data

In [4]:
import warnings
warnings.filterwarnings('ignore')

# Missing Data Threshold
threshold_data = float(os.getenv("THRESHOLD_MISSING_DATA", None))
print(f'Threshold Missing Data: {int(threshold_data * 100)}%')

# For each Tangara sensor
for id_tangara_sensor in df_pm25_raw.columns:
    df_pm25_sensor = df_pm25_raw[[id_tangara_sensor]]
    # To be checked
    to_be_checked, data_percent, missing_data_percent = missing_data(df_pm25_sensor, threshold_data)
    if to_be_checked:
        print(f"Tangara Sensor: {id_tangara_sensor}, To be checked: {to_be_checked}, Data: {data_percent}%, Missing Data: {missing_data_percent}%, Threshold: {threshold_data}%")

        # Drop Tangara Sensor from original dataframe
        df_pm25_raw = df_pm25_raw.drop(id_tangara_sensor, axis=1)

2024-03-01 17:19:40.619 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_3BEA, To be checked: False, Data: 90%, Missing Data: 10%, Threshold: 80%
2024-03-01 17:19:40.623 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_421A, To be checked: False, Data: 80%, Missing Data: 20%, Threshold: 80%
2024-03-01 17:19:40.627 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_422A, To be checked: False, Data: 80%, Missing Data: 20%, Threshold: 80%
2024-03-01 17:19:40.631 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_5636, To be checked: False, Data: 85%, Missing Data: 15%, Threshold: 80%
2024-03-01 17:19:40.635 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_D282, To be checked: False, Data: 86%, Missing Data: 14%, Threshold: 80%

Threshold Missing Data: 80%

## Data Correlation

In [5]:
# Data Correlation Threshold
threshold_correlation = float(os.getenv("THRESHOLD_CORRELATION_DATA", None))
print(f'Threshold Correlation Data: {int(threshold_correlation * 100)}%')

# Tangara Sensor Reference
ID_TANGARA_REFERENCE=os.getenv("ID_TANGARA_REFERENCE", None)

# Tangara Sensors Target
IDS_TANGARA_TARGETS=os.getenv("IDS_TANGARA_TARGETS", None)
IDS_TANGARA_TARGETS = IDS_TANGARA_TARGETS.split(',') if IDS_TANGARA_TARGETS else ID_TANGARA_REFERENCE

# print(f"Tangara Sensor Reference: {ID_TANGARA_REFERENCE}, Tangara Sensors Target: {IDS_TANGARA_TARGETS}")

# Reference Tangara Sensor
df_tangara_reference = df_pm25_raw[[ID_TANGARA_REFERENCE]]

# For each Tangara Sensor Target
for id_tangara in IDS_TANGARA_TARGETS:
    if id_tangara in df_pm25_raw.columns:
        # Target Tangara Sensor
        df_tangara_target = df_pm25_raw[[id_tangara]]

        # To be checked
        if not math.isnan(df_tangara_reference.std()):
            has_corr, corr = correlation_data(df_tangara_reference, df_tangara_target, threshold_correlation)
            if not has_corr:
                print(f"Tangara Sensor Reference: {ID_TANGARA_REFERENCE}, Tangara Sensors Target: {id_tangara}, There is correlation: {has_corr}, Correlation: {float("{:.2f}".format(corr))}, Threshold: {threshold_correlation}")

                # Drop Tangara Sensor from original dataframe
                df_pm25_raw = df_pm25_raw.drop(id_tangara, axis=1)

2024-03-01 17:19:40.671 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_5636, Tangara Sensors Target: TANGARA_3BEA, There is correlation: True, Correlation: 0.89, Threshold: 0.7
2024-03-01 17:19:40.687 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_5636, Tangara Sensors Target: TANGARA_421A, There is correlation: True, Correlation: 0.88, Threshold: 0.7
2024-03-01 17:19:40.711 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_5636, Tangara Sensors Target: TANGARA_422A, There is correlation: True, Correlation: 0.97, Threshold: 0.7

Threshold Correlation Data: 70%

2024-03-01 17:19:40.758 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_5636, Tangara Sensors Target: TANGARA_5636, There is correlation: True, Correlation: 1.0, Threshold: 0.7
2024-03-01 17:19:40.795 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_5636, Tangara Sensors Target: TANGARA_D282, There is correlation: True, Correlation: 0.95, Threshold: 0.7

## Histograms

In [6]:
# Plot Histograms
plot_hist(df_pm25_raw)

2024-03-01 17:19:40.833 | DEBUG    | utils:plot_hist:514 - Plot Histograms: False

## Boxplots

In [7]:
# Plot Boxplots
plot_boxes(df_pm25_raw)

2024-03-01 17:19:40.871 | DEBUG    | utils:plot_boxes:547 - Plot Boxplots: False

## Lineplots

In [8]:
# Plot Lineplots
plot_lines(df_pm25_raw)

2024-03-01 17:19:40.905 | DEBUG    | utils:plot_lines:588 - Plot Lineplots: False

## Drop PM2.5 Outliers

In [9]:
# Drop PM2.5 Outliers
df_pm25_clean, resume = drop_pm25_outliers(df_pm25_raw)

2024-03-01 17:19:40.983 | DEBUG    | utils:drop_pm25_outliers:651 - Drop PM2.5 Outliers: <class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 25920 entries, 2023-12-30 00:00:00-05:00 to 2024-01-07 23:59:30-05:00
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   TANGARA_3BEA  22100 non-null  float64
 1   TANGARA_421A  19606 non-null  float64
 2   TANGARA_422A  19455 non-null  float64
 3   TANGARA_5636  20740 non-null  float64
 4   TANGARA_D282  21124 non-null  float64
dtypes: float64(5)
memory usage: 1.2 MB

In [10]:
# Describe Data
df_pm25_raw.describe()

       TANGARA_3BEA  TANGARA_421A  TANGARA_422A  TANGARA_5636  TANGARA_D282
count  22100.000000  19606.000000  19455.000000  20740.000000  21124.000000
mean       6.309186      5.793890      5.757903      6.001639      7.129426
std        3.094601      2.642077      2.736385      2.806452      3.512930
min        1.000000      1.000000      1.000000      1.000000      1.000000
25%        4.000000      4.000000      4.000000      4.000000      5.000000
50%        6.000000      5.000000      5.000000      6.000000      6.000000
75%        8.000000      7.000000      7.000000      8.000000      9.000000
max       16.000000     14.000000     14.000000     14.000000     17.000000

In [11]:
# Describe Data
df_pm25_clean.describe()

       TANGARA_3BEA  TANGARA_421A  TANGARA_422A  TANGARA_5636  TANGARA_D282
count  22100.000000  19606.000000  19455.000000  20740.000000  21124.000000
mean       6.309186      5.793890      5.757903      6.001639      7.129426
std        3.094601      2.642077      2.736385      2.806452      3.512930
min        1.000000      1.000000      1.000000      1.000000      1.000000
25%        4.000000      4.000000      4.000000      4.000000      5.000000
50%        6.000000      5.000000      5.000000      6.000000      6.000000
75%        8.000000      7.000000      7.000000      8.000000      9.000000
max       16.000000     14.000000     14.000000     14.000000     17.000000

## Histograms

In [12]:
# Plot Histograms
plot_hist(df_pm25_clean)

2024-03-01 17:19:41.074 | DEBUG    | utils:plot_hist:514 - Plot Histograms: False

## Boxplots

In [13]:
# Plot Boxplots
plot_boxes(df_pm25_clean)

2024-03-01 17:19:41.085 | DEBUG    | utils:plot_boxes:547 - Plot Boxplots: False

## Lineplots

In [14]:
# Plot Lineplots
plot_lines(df_pm25_clean)

2024-03-01 17:19:41.097 | DEBUG    | utils:plot_lines:588 - Plot Lineplots: False

In [15]:
# Save PM2.5 Data Frame Sensors into CSV file
df_to_csv(df_pm25_clean, "pm25_clean.csv", datafolder='1_clean')

2024-03-01 17:19:41.623 | DEBUG    | utils:df_to_csv:311 - Save DataFrame: /home/sebaxtian/Workspaces/Tangara/tangara-evaluation/src/data/1_clean/pm25_clean.csv