In [1]:
import os
import math
import pandas as pd
from dotenv import load_dotenv

# Explicitly providing path to '.env'
from pathlib import Path  # Python 3.6+ only
# Load .env variables
_ = load_dotenv(dotenv_path=f"{Path().resolve().parents[1]}/src/.env")

# with the new api
from importnb import imports
with imports("ipynb"):
    from utils import to_timestamp, df_data_sensors, missing_data, correlation_data, df_to_csv, df_from_csv

PM2.5: 35.9, AQI: 102
PM2.5: 35.9, Measure Level: MeasureLevels.UNHEALTHY_FOR_SENSITIVE_GROUPS, Range Values: Min: 35.5, Max: 55.4
AQI: 102, Measure Level: MeasureLevels.UNHEALTHY_FOR_SENSITIVE_GROUPS, Range Values: Min: 101, Max: 150

## Reference

In [2]:
# Load Tangara Reference
df_reference = df_from_csv("reference.csv", datafolder='2_features', dtindex=False)
print(f"Tangara Sensor Reference: {df_reference['ID'].values[0]}")

df_reference

2024-07-15 18:49:13.643 | DEBUG    | utils:df_from_csv:340 - Load DataFrame: /home/sebaxtian/Workspaces/Tangara/tangara-evaluation/src/data/2_features/reference.csv

Tangara Sensor Reference: TANGARA_25BE

,ID,GEOHASH,MAC,GEOLOCATION,LATITUDE,LONGITUDE
0,TANGARA_25BE,d29e6de,D29ESP32DE725BE,3.3982086181640625 -76.52595520019531,3.398209,-76.525955

## Targets

In [3]:
# Load Tangara Targets
df_targets = df_from_csv("targets.csv", datafolder='2_features', dtindex=False)
print(f"Total Tangara Sensor Targets: {len(df_targets)}")

df_targets

2024-07-15 18:49:13.671 | DEBUG    | utils:df_from_csv:340 - Load DataFrame: /home/sebaxtian/Workspaces/Tangara/tangara-evaluation/src/data/2_features/targets.csv

Total Tangara Sensor Targets: 23

,ID,GEOHASH,MAC,GEOLOCATION,LATITUDE,LONGITUDE
0,TANGARA_B7BE,d29e6de,D29ESP32DE0B7BE,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
1,TANGARA_C752,d29e6de,D29ESP32DE0C752,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
2,TANGARA_A682,d29e6d7,D29ESP32DE3A682,3.3968353271484375 -76.52595520019531,3.396835,-76.525955
3,TANGARA_ADD6,d29e6de,D29ESP32DE3ADD6,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
4,TANGARA_B08A,d29e6de,D29ESP32DE3B08A,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
5,TANGARA_B9CA,d29e6de,D29ESP32DE3B9CA,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
6,TANGARA_BC5A,d29e6ds,D29ESP32DE3BC5A,3.3982086181640625 -76.52458190917969,3.398209,-76.524582
7,TANGARA_BCC6,d29e6de,D29ESP32DE3BCC6,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
8,TANGARA_BD5E,d29e6de,D29ESP32DE3BD5E,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
9,TANGARA_BE12,d29e6de,D29ESP32DE3BE12,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
10,TANGARA_79CA,d29e6de,D29ESP32DE679CA,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
11,TANGARA_0E26,d29e6de,D29ESP32DE70E26,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
12,TANGARA_1402,d29e6de,D29ESP32DE71402,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
13,TANGARA_157E,d29e6de,D29ESP32DE7157E,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
14,TANGARA_18DA,d29e6de,D29ESP32DE718DA,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
15,TANGARA_1DE2,d29e6de,D29ESP32DE71DE2,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
16,TANGARA_211E,d29e6de,D29ESP32DE7211E,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
17,TANGARA_25F2,d29e6de,D29ESP32DE725F2,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
18,TANGARA_298A,d29e6de,D29ESP32DE7298A,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
19,TANGARA_3376,d29e6de,D29ESP32DE73376,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
20,TANGARA_A43A,d29e6ds,D29ESP32DEFA43A,3.3982086181640625 -76.52458190917969,3.398209,-76.524582
21,TANGARA_C17E,d29e6de,D29ESP32DEFC17E,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
22,TANGARA_CA62,d29e6de,D29ESP32DEFCA62,3.3982086181640625 -76.52595520019531,3.398209,-76.525955

## Tangaras

In [4]:
# Tangaras from Reference and Targets
df_tangaras = pd.concat([df_reference, df_targets], ignore_index=True)
print(f"Total Tangara Sensors: {len(df_tangaras)}")

df_tangaras

Total Tangara Sensors: 24

,ID,GEOHASH,MAC,GEOLOCATION,LATITUDE,LONGITUDE
0,TANGARA_25BE,d29e6de,D29ESP32DE725BE,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
1,TANGARA_B7BE,d29e6de,D29ESP32DE0B7BE,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
2,TANGARA_C752,d29e6de,D29ESP32DE0C752,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
3,TANGARA_A682,d29e6d7,D29ESP32DE3A682,3.3968353271484375 -76.52595520019531,3.396835,-76.525955
4,TANGARA_ADD6,d29e6de,D29ESP32DE3ADD6,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
5,TANGARA_B08A,d29e6de,D29ESP32DE3B08A,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
6,TANGARA_B9CA,d29e6de,D29ESP32DE3B9CA,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
7,TANGARA_BC5A,d29e6ds,D29ESP32DE3BC5A,3.3982086181640625 -76.52458190917969,3.398209,-76.524582
8,TANGARA_BCC6,d29e6de,D29ESP32DE3BCC6,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
9,TANGARA_BD5E,d29e6de,D29ESP32DE3BD5E,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
10,TANGARA_BE12,d29e6de,D29ESP32DE3BE12,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
11,TANGARA_79CA,d29e6de,D29ESP32DE679CA,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
12,TANGARA_0E26,d29e6de,D29ESP32DE70E26,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
13,TANGARA_1402,d29e6de,D29ESP32DE71402,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
14,TANGARA_157E,d29e6de,D29ESP32DE7157E,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
15,TANGARA_18DA,d29e6de,D29ESP32DE718DA,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
16,TANGARA_1DE2,d29e6de,D29ESP32DE71DE2,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
17,TANGARA_211E,d29e6de,D29ESP32DE7211E,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
18,TANGARA_25F2,d29e6de,D29ESP32DE725F2,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
19,TANGARA_298A,d29e6de,D29ESP32DE7298A,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
20,TANGARA_3376,d29e6de,D29ESP32DE73376,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
21,TANGARA_A43A,d29e6ds,D29ESP32DEFA43A,3.3982086181640625 -76.52458190917969,3.398209,-76.524582
22,TANGARA_C17E,d29e6de,D29ESP32DEFC17E,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
23,TANGARA_CA62,d29e6de,D29ESP32DEFCA62,3.3982086181640625 -76.52595520019531,3.398209,-76.525955

## Temperature Raw Data

In [5]:
# Start Date Time ISO 8601 Format, TZ='America/Bogota' -05:00
START_ISO8601_DATETIME = os.getenv("START_ISO8601_DATETIME", None)
start_timestamp = to_timestamp(START_ISO8601_DATETIME)
# End Date Time ISO 8601 Format, TZ='America/Bogota' -05:00
END_ISO8601_DATETIME = os.getenv("END_ISO8601_DATETIME", None)
end_timestamp = to_timestamp(os.getenv("END_ISO8601_DATETIME", None))

# GROUP BY TIME
GROUP_BY_TIME = os.getenv("GROUP_BY_TIME", None)

print(f'Since: {START_ISO8601_DATETIME} -> {start_timestamp}, Until: {END_ISO8601_DATETIME} -> {end_timestamp}')
print(f"Group by Time: {GROUP_BY_TIME}")

2024-07-15 18:49:13.713 | DEBUG    | utils:to_timestamp:99 - datetime_iso8601: 2024-07-15T19:49:00-05:00, Timestamp: 1721090940000
2024-07-15 18:49:13.715 | DEBUG    | utils:to_timestamp:99 - datetime_iso8601: 2024-07-15T20:49:00-05:00, Timestamp: 1721094540000

Since: 2024-07-15T19:49:00-05:00 -> 1721090940000, Until: 2024-07-15T20:49:00-05:00 -> 1721094540000
Group by Time: 30s

In [6]:
# Temperature Data Frame Sensors
df_temp_raw = df_data_sensors(df_tangaras, start_timestamp, end_timestamp, 'tmp', GROUP_BY_TIME)
df_temp_raw

2024-07-15 18:49:13.724 | DEBUG    | utils:query_measure:192 - sql_query: SELECT last("tmp") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE725BE') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null); SELECT last("tmp") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE0B7BE') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null); SELECT last("tmp") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE0C752') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null); SELECT last("tmp") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE3A682') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null); SELECT last("tmp") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE3ADD6') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null); SELECT last("tmp") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE3B08A') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null); SELECT last("tmp") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE3B9CA') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null); SELECT last("tmp") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE3BC5A') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null); SELECT last("tmp") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE3BCC6') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null); SELECT last("tmp") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE3BD5E') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null); SELECT last("tmp") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE3BE12') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null); SELECT last("tmp") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE679CA') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null); SELECT last("tmp") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE70E26') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null); SELECT last("tmp") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE71402') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null); SELECT last("tmp") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE7157E') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null); SELECT last("tmp") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE718DA') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null); SELECT last("tmp") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE71DE2') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null); SELECT last("tmp") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE7211E') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null); SELECT last("tmp") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE725F2') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null); SELECT last("tmp") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE7298A') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null); SELECT last("tmp") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE73376') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null); SELECT last("tmp") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DEFA43A') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null); SELECT last("tmp") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DEFC17E') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null); SELECT last("tmp") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DEFCA62') AND time >= 1721090940000ms AND time <= 1721094540000ms GROUP BY time(30s) fill(null)
2024-07-15 18:49:14.120 | DEBUG    | utils:request_influxdb:131 - response: <Response [200]>
2024-07-15 18:49:14.210 | DEBUG    | utils:df_data_sensors:480 - Measure Data Frame Sensors: <class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 121 entries, 2024-07-15 19:49:00-05:00 to 2024-07-15 20:49:00-05:00
Freq: 30S
Data columns (total 24 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   TANGARA_25BE  110 non-null    float64
 1   TANGARA_B7BE  81 non-null     float64
 2   TANGARA_C752  88 non-null     float64
 3   TANGARA_A682  118 non-null    float64
 4   TANGARA_ADD6  120 non-null    float64
 5   TANGARA_B08A  111 non-null    float64
 6   TANGARA_B9CA  120 non-null    float64
 7   TANGARA_BC5A  117 non-null    float64
 8   TANGARA_BCC6  113 non-null    float64
 9   TANGARA_BD5E  113 non-null    float64
 10  TANGARA_BE12  108 non-null    float64
 11  TANGARA_79CA  120 non-null    float64
 12  TANGARA_0E26  115 non-null    float64
 13  TANGARA_1402  120 non-null    float64
 14  TANGARA_157E  109 non-null    float64
 15  TANGARA_18DA  120 non-null    float64
 16  TANGARA_1DE2  120 non-null    float64
 17  TANGARA_211E  120 non-null    float64
 18  TANGARA_25F2  117 non-null    float64
 19  TANGARA_298A  109 non-null    float64
 20  TANGARA_3376  115 non-null    float64
 21  TANGARA_A43A  120 non-null    float64
 22  TANGARA_C17E  120 non-null    float64
 23  TANGARA_CA62  120 non-null    float64
dtypes: float64(24)
memory usage: 23.6 KB

,TANGARA_25BE,TANGARA_B7BE,TANGARA_C752,TANGARA_A682,TANGARA_ADD6,TANGARA_B08A,TANGARA_B9CA,TANGARA_BC5A,TANGARA_BCC6,TANGARA_BD5E,...,TANGARA_157E,TANGARA_18DA,TANGARA_1DE2,TANGARA_211E,TANGARA_25F2,TANGARA_298A,TANGARA_3376,TANGARA_A43A,TANGARA_C17E,TANGARA_CA62
DATETIME,,,,,,,,,,,,,,,,,,,,,
2024-07-15 19:49:00-05:00,32.69,NaN,28.17,35.48,33.86,34.19,35.39,35.35,38.55,33.91,...,34.67,32.23,35.96,34.57,32.59,36.61,32.80,35.05,35.29,33.19
2024-07-15 19:49:30-05:00,NaN,34.40,28.17,35.42,33.85,34.18,35.39,35.40,38.60,33.91,...,34.66,32.16,35.98,34.54,32.55,NaN,32.83,35.02,35.26,33.18
2024-07-15 19:50:00-05:00,32.66,34.39,28.17,35.44,33.82,34.19,35.39,35.40,38.62,33.91,...,34.66,32.19,35.98,34.57,32.56,36.60,32.79,34.99,35.19,33.16
2024-07-15 19:50:30-05:00,32.66,34.39,28.17,35.38,33.82,34.21,35.39,35.38,38.60,33.88,...,34.66,32.18,35.96,34.60,32.56,36.63,32.77,35.00,35.20,33.16
2024-07-15 19:51:00-05:00,32.64,NaN,28.17,35.35,33.84,34.24,35.38,35.37,38.59,33.91,...,34.64,32.13,36.00,34.57,32.55,36.61,32.79,34.99,35.21,33.21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-07-15 20:47:00-05:00,32.44,NaN,NaN,35.42,33.81,34.06,35.42,35.13,38.25,33.72,...,34.68,32.04,35.88,34.61,32.42,36.68,32.74,34.64,35.31,33.11
2024-07-15 20:47:30-05:00,32.43,34.02,NaN,35.40,33.81,34.08,35.42,35.13,38.22,33.71,...,34.64,32.04,35.88,34.61,32.40,36.67,32.72,34.65,35.33,33.08
2024-07-15 20:48:00-05:00,32.43,NaN,NaN,35.35,33.82,34.08,35.43,35.13,38.18,33.71,...,NaN,32.04,35.88,34.66,32.35,NaN,32.74,34.64,35.36,33.06
2024-07-15 20:48:30-05:00,32.37,NaN,NaN,35.35,33.82,34.04,35.43,35.15,38.22,33.71,...,34.67,32.01,35.88,34.64,32.35,NaN,32.74,34.60,35.33,33.08
2024-07-15 20:49:00-05:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Descriptive Statistics

In [7]:
# Describe Data
df_temp_raw.describe()

,TANGARA_25BE,TANGARA_B7BE,TANGARA_C752,TANGARA_A682,TANGARA_ADD6,TANGARA_B08A,TANGARA_B9CA,TANGARA_BC5A,TANGARA_BCC6,TANGARA_BD5E,...,TANGARA_157E,TANGARA_18DA,TANGARA_1DE2,TANGARA_211E,TANGARA_25F2,TANGARA_298A,TANGARA_3376,TANGARA_A43A,TANGARA_C17E,TANGARA_CA62
count,110.000000,81.000000,8.800000e+01,118.000000,120.000000,111.000000,120.000000,117.000000,113.000000,113.000000,...,109.000000,120.000000,120.000000,120.000000,117.000000,109.000000,115.000000,120.000000,120.000000,120.000000
mean,32.551727,34.247654,2.817000e+01,35.360339,33.805583,34.134865,35.365833,35.257350,38.397522,33.799292,...,34.630917,32.127583,35.870000,34.550583,32.462479,36.579083,32.767391,34.869417,35.214083,33.180000
std,0.065942,0.148503,1.071922e-14,0.037937,0.024385,0.074856,0.029408,0.074271,0.129059,0.065679,...,0.052644,0.045835,0.058626,0.042094,0.052767,0.036731,0.039804,0.124477,0.059246,0.076158
min,32.370000,33.980000,2.817000e+01,35.260000,33.760000,34.010000,35.310000,35.130000,38.150000,33.680000,...,34.530000,31.990000,35.720000,34.460000,32.350000,36.520000,32.700000,34.600000,35.090000,33.060000
25%,32.490000,34.090000,2.817000e+01,35.340000,33.790000,34.070000,35.350000,35.180000,38.260000,33.740000,...,34.590000,32.100000,35.840000,34.525000,32.420000,36.550000,32.735000,34.750000,35.170000,33.120000
50%,32.570000,34.280000,2.817000e+01,35.350000,33.810000,34.120000,35.360000,35.260000,38.430000,33.790000,...,34.630000,32.130000,35.880000,34.560000,32.460000,36.570000,32.760000,34.880000,35.210000,33.160000
75%,32.600000,34.370000,2.817000e+01,35.380000,33.820000,34.210000,35.390000,35.330000,38.490000,33.850000,...,34.660000,32.150000,35.900000,34.570000,32.490000,36.600000,32.800000,34.982500,35.260000,33.235000
max,32.690000,34.470000,2.817000e+01,35.480000,33.860000,34.260000,35.430000,35.400000,38.620000,33.950000,...,34.800000,32.230000,36.030000,34.660000,32.590000,36.680000,32.860000,35.050000,35.360000,33.330000

## Missing Data

In [8]:
import warnings
warnings.filterwarnings('ignore')

# Missing Data Threshold
threshold_data = float(os.getenv("THRESHOLD_MISSING_DATA", None))
print(f'Threshold Missing Data: {int(threshold_data * 100)}%')

# DataFrame Report for Missing Data Temperature
df_temp_missing_data = pd.DataFrame({'ID': [], 'TO_BE_CHECKED': [], 'DATA_PERCENT': [], 'MISSING_DATA_PERCENT': [], 'THRESHOLD_MISSING_DATA': []})

# For each Tangara sensor
for id_tangara_sensor in df_temp_raw.columns:
    df_temp_sensor = df_temp_raw[[id_tangara_sensor]]
    # To be checked
    to_be_checked, data_percent, missing_data_percent = missing_data(df_temp_sensor, threshold_data)
    if to_be_checked:
        print(f"Tangara Sensor: {id_tangara_sensor}, To be checked: {to_be_checked}, Data: {data_percent}%, Missing Data: {missing_data_percent}%, Threshold: {threshold_data}%")
        # Drop Tangara Sensor from original dataframe
        # df_temp_raw = df_temp_raw.drop(id_tangara_sensor, axis=1)
    
    # Insert into DataFrame Report
    df_temp_missing_data.loc[len(df_temp_missing_data.index)] = [id_tangara_sensor, to_be_checked, data_percent, missing_data_percent, threshold_data]

df_temp_missing_data

2024-07-15 18:49:14.352 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_25BE, To be checked: False, Data: 91%, Missing Data: 9%, Threshold: 80%
2024-07-15 18:49:14.357 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_B7BE, To be checked: True, Data: 67%, Missing Data: 33%, Threshold: 80%
2024-07-15 18:49:14.362 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_C752, To be checked: True, Data: 73%, Missing Data: 27%, Threshold: 80%
2024-07-15 18:49:14.367 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_A682, To be checked: False, Data: 98%, Missing Data: 2%, Threshold: 80%
2024-07-15 18:49:14.372 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_ADD6, To be checked: False, Data: 99%, Missing Data: 1%, Threshold: 80%
2024-07-15 18:49:14.376 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_B08A, To be checked: False, Data: 92%, Missing Data: 8%, Threshold: 80%
2024-07-15 18:49:14.381 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_B9CA, To be checked: False, Data: 99%, Missing Data: 1%, Threshold: 80%
2024-07-15 18:49:14.385 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_BC5A, To be checked: False, Data: 97%, Missing Data: 3%, Threshold: 80%
2024-07-15 18:49:14.389 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_BCC6, To be checked: False, Data: 93%, Missing Data: 7%, Threshold: 80%
2024-07-15 18:49:14.394 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_BD5E, To be checked: False, Data: 93%, Missing Data: 7%, Threshold: 80%
2024-07-15 18:49:14.399 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_BE12, To be checked: False, Data: 89%, Missing Data: 11%, Threshold: 80%
2024-07-15 18:49:14.404 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_79CA, To be checked: False, Data: 99%, Missing Data: 1%, Threshold: 80%
2024-07-15 18:49:14.408 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_0E26, To be checked: False, Data: 95%, Missing Data: 5%, Threshold: 80%
2024-07-15 18:49:14.412 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_1402, To be checked: False, Data: 99%, Missing Data: 1%, Threshold: 80%
2024-07-15 18:49:14.417 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_157E, To be checked: False, Data: 90%, Missing Data: 10%, Threshold: 80%
2024-07-15 18:49:14.422 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_18DA, To be checked: False, Data: 99%, Missing Data: 1%, Threshold: 80%
2024-07-15 18:49:14.426 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_1DE2, To be checked: False, Data: 99%, Missing Data: 1%, Threshold: 80%
2024-07-15 18:49:14.430 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_211E, To be checked: False, Data: 99%, Missing Data: 1%, Threshold: 80%
2024-07-15 18:49:14.435 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_25F2, To be checked: False, Data: 97%, Missing Data: 3%, Threshold: 80%
2024-07-15 18:49:14.440 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_298A, To be checked: False, Data: 90%, Missing Data: 10%, Threshold: 80%
2024-07-15 18:49:14.444 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_3376, To be checked: False, Data: 95%, Missing Data: 5%, Threshold: 80%
2024-07-15 18:49:14.448 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_A43A, To be checked: False, Data: 99%, Missing Data: 1%, Threshold: 80%
2024-07-15 18:49:14.452 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_C17E, To be checked: False, Data: 99%, Missing Data: 1%, Threshold: 80%
2024-07-15 18:49:14.457 | DEBUG    | utils:missing_data:230 - Tangara Sensor: TANGARA_CA62, To be checked: False, Data: 99%, Missing Data: 1%, Threshold: 80%

Threshold Missing Data: 80%
Tangara Sensor: TANGARA_B7BE, To be checked: True, Data: 67%, Missing Data: 33%, Threshold: 0.8%
Tangara Sensor: TANGARA_C752, To be checked: True, Data: 73%, Missing Data: 27%, Threshold: 0.8%

,ID,TO_BE_CHECKED,DATA_PERCENT,MISSING_DATA_PERCENT,THRESHOLD_MISSING_DATA
0,TANGARA_25BE,False,91,9,0.8
1,TANGARA_B7BE,True,67,33,0.8
2,TANGARA_C752,True,73,27,0.8
3,TANGARA_A682,False,98,2,0.8
4,TANGARA_ADD6,False,99,1,0.8
5,TANGARA_B08A,False,92,8,0.8
6,TANGARA_B9CA,False,99,1,0.8
7,TANGARA_BC5A,False,97,3,0.8
8,TANGARA_BCC6,False,93,7,0.8
9,TANGARA_BD5E,False,93,7,0.8
10,TANGARA_BE12,False,89,11,0.8
11,TANGARA_79CA,False,99,1,0.8
12,TANGARA_0E26,False,95,5,0.8
13,TANGARA_1402,False,99,1,0.8
14,TANGARA_157E,False,90,10,0.8
15,TANGARA_18DA,False,99,1,0.8
16,TANGARA_1DE2,False,99,1,0.8
17,TANGARA_211E,False,99,1,0.8
18,TANGARA_25F2,False,97,3,0.8
19,TANGARA_298A,False,90,10,0.8
20,TANGARA_3376,False,95,5,0.8
21,TANGARA_A43A,False,99,1,0.8
22,TANGARA_C17E,False,99,1,0.8
23,TANGARA_CA62,False,99,1,0.8

In [9]:
# Save DataFrame Report for Missing Data Temperature into CSV file
df_temp_missing_data.set_index('ID', inplace=True)
df_to_csv(df_temp_missing_data, "temp_missing.csv", datafolder='2_features')

2024-07-15 18:49:14.482 | DEBUG    | utils:df_to_csv:311 - Save DataFrame: /home/sebaxtian/Workspaces/Tangara/tangara-evaluation/src/data/2_features/temp_missing.csv

## Data Correlation

In [10]:
# Data Correlation Threshold
threshold_correlation = float(os.getenv("THRESHOLD_CORRELATION_DATA", None))
print(f'Threshold Correlation Data: {int(threshold_correlation * 100)}%')

# Tangara Sensor Reference
ID_TANGARA_REFERENCE = df_reference['ID'].values[0]
df_temp_reference = df_temp_raw[[ID_TANGARA_REFERENCE]]

# DataFrame Report for Data Correlation Temperature
df_temp_correlation_data = pd.DataFrame({'ID_REFERENCE': [], 'ID_TARGET': [], 'THERE_IS_CORRELATION': [], 'CORRELATION_VALUE': [], 'THRESHOLD_CORRELATION': []})

# For each Tangara Sensor Target
for id_tangara_sensor in df_temp_raw.columns:
    if id_tangara_sensor != ID_TANGARA_REFERENCE:
        # Target Tangara Sensor
        df_temp_target = df_temp_raw[[id_tangara_sensor]]
        
        # To be checked
        if not math.isnan(df_temp_reference.std()):
            has_corr, corr = correlation_data(df_temp_reference, df_temp_target, threshold_correlation)
            if not has_corr:
                print(f"Tangara Sensor Reference: {ID_TANGARA_REFERENCE}, Tangara Sensors Target: {df_temp_target.columns[0]}, There is correlation: {has_corr}, Correlation: {float("{:.2f}".format(corr))}, Threshold: {threshold_correlation}")

                # Drop Tangara Sensor from original dataframe
                # df_temp_raw = df_temp_raw.drop(id_tangara, axis=1)
            
            # Insert into DataFrame Report
            df_temp_correlation_data.loc[len(df_temp_correlation_data.index)] = [ID_TANGARA_REFERENCE, df_temp_target.columns[0], has_corr, float("{:.2f}".format(corr)), threshold_correlation]

df_temp_correlation_data

2024-07-15 18:49:14.501 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_B7BE, There is correlation: True, Correlation: 0.92, Threshold: 0.8
2024-07-15 18:49:14.506 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_C752, There is correlation: False, Correlation: 0.0, Threshold: 0.8
2024-07-15 18:49:14.512 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_A682, There is correlation: False, Correlation: -0.09, Threshold: 0.8
2024-07-15 18:49:14.522 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_ADD6, There is correlation: False, Correlation: 0.29, Threshold: 0.8
2024-07-15 18:49:14.528 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_B08A, There is correlation: True, Correlation: 0.87, Threshold: 0.8
2024-07-15 18:49:14.535 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_B9CA, There is correlation: False, Correlation: -0.38, Threshold: 0.8
2024-07-15 18:49:14.542 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_BC5A, There is correlation: True, Correlation: 0.9, Threshold: 0.8
2024-07-15 18:49:14.549 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_BCC6, There is correlation: True, Correlation: 0.91, Threshold: 0.8

Threshold Correlation Data: 80%
Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_C752, There is correlation: False, Correlation: 0.0, Threshold: 0.8
Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_A682, There is correlation: False, Correlation: -0.09, Threshold: 0.8
Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_ADD6, There is correlation: False, Correlation: 0.29, Threshold: 0.8
Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_B9CA, There is correlation: False, Correlation: -0.38, Threshold: 0.8

2024-07-15 18:49:14.556 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_BD5E, There is correlation: True, Correlation: 0.89, Threshold: 0.8
2024-07-15 18:49:14.562 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_BE12, There is correlation: False, Correlation: 0.24, Threshold: 0.8
2024-07-15 18:49:14.569 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_79CA, There is correlation: False, Correlation: 0.55, Threshold: 0.8
2024-07-15 18:49:14.575 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_0E26, There is correlation: False, Correlation: 0.78, Threshold: 0.8
2024-07-15 18:49:14.581 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_1402, There is correlation: True, Correlation: 0.93, Threshold: 0.8
2024-07-15 18:49:14.587 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_157E, There is correlation: False, Correlation: -0.35, Threshold: 0.8
2024-07-15 18:49:14.594 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_18DA, There is correlation: False, Correlation: 0.68, Threshold: 0.8
2024-07-15 18:49:14.600 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_1DE2, There is correlation: False, Correlation: 0.64, Threshold: 0.8
2024-07-15 18:49:14.606 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_211E, There is correlation: False, Correlation: -0.54, Threshold: 0.8
2024-07-15 18:49:14.612 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_25F2, There is correlation: True, Correlation: 0.89, Threshold: 0.8
2024-07-15 18:49:14.619 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_298A, There is correlation: False, Correlation: -0.56, Threshold: 0.8
2024-07-15 18:49:14.626 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_3376, There is correlation: False, Correlation: 0.25, Threshold: 0.8
2024-07-15 18:49:14.632 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_A43A, There is correlation: True, Correlation: 0.93, Threshold: 0.8
2024-07-15 18:49:14.639 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_C17E, There is correlation: False, Correlation: -0.32, Threshold: 0.8
2024-07-15 18:49:14.645 | DEBUG    | utils:correlation_data:287 - Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_CA62, There is correlation: False, Correlation: 0.48, Threshold: 0.8

Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_BE12, There is correlation: False, Correlation: 0.24, Threshold: 0.8
Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_79CA, There is correlation: False, Correlation: 0.55, Threshold: 0.8
Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_0E26, There is correlation: False, Correlation: 0.78, Threshold: 0.8
Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_157E, There is correlation: False, Correlation: -0.35, Threshold: 0.8
Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_18DA, There is correlation: False, Correlation: 0.68, Threshold: 0.8
Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_1DE2, There is correlation: False, Correlation: 0.64, Threshold: 0.8
Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_211E, There is correlation: False, Correlation: -0.54, Threshold: 0.8
Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_298A, There is correlation: False, Correlation: -0.56, Threshold: 0.8
Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_3376, There is correlation: False, Correlation: 0.25, Threshold: 0.8
Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_C17E, There is correlation: False, Correlation: -0.32, Threshold: 0.8
Tangara Sensor Reference: TANGARA_25BE, Tangara Sensors Target: TANGARA_CA62, There is correlation: False, Correlation: 0.48, Threshold: 0.8

,ID_REFERENCE,ID_TARGET,THERE_IS_CORRELATION,CORRELATION_VALUE,THRESHOLD_CORRELATION
0,TANGARA_25BE,TANGARA_B7BE,True,0.92,0.8
1,TANGARA_25BE,TANGARA_C752,False,0.00,0.8
2,TANGARA_25BE,TANGARA_A682,False,-0.09,0.8
3,TANGARA_25BE,TANGARA_ADD6,False,0.29,0.8
4,TANGARA_25BE,TANGARA_B08A,True,0.87,0.8
5,TANGARA_25BE,TANGARA_B9CA,False,-0.38,0.8
6,TANGARA_25BE,TANGARA_BC5A,True,0.90,0.8
7,TANGARA_25BE,TANGARA_BCC6,True,0.91,0.8
8,TANGARA_25BE,TANGARA_BD5E,True,0.89,0.8
9,TANGARA_25BE,TANGARA_BE12,False,0.24,0.8
10,TANGARA_25BE,TANGARA_79CA,False,0.55,0.8
11,TANGARA_25BE,TANGARA_0E26,False,0.78,0.8
12,TANGARA_25BE,TANGARA_1402,True,0.93,0.8
13,TANGARA_25BE,TANGARA_157E,False,-0.35,0.8
14,TANGARA_25BE,TANGARA_18DA,False,0.68,0.8
15,TANGARA_25BE,TANGARA_1DE2,False,0.64,0.8
16,TANGARA_25BE,TANGARA_211E,False,-0.54,0.8
17,TANGARA_25BE,TANGARA_25F2,True,0.89,0.8
18,TANGARA_25BE,TANGARA_298A,False,-0.56,0.8
19,TANGARA_25BE,TANGARA_3376,False,0.25,0.8
20,TANGARA_25BE,TANGARA_A43A,True,0.93,0.8
21,TANGARA_25BE,TANGARA_C17E,False,-0.32,0.8
22,TANGARA_25BE,TANGARA_CA62,False,0.48,0.8

In [11]:
# Save DataFrame Report for Data Correlation Temperature into CSV file
df_temp_correlation_data.set_index('ID_TARGET', inplace=True)
df_to_csv(df_temp_correlation_data, "temp_correlation.csv", datafolder='2_features')

2024-07-15 18:49:14.675 | DEBUG    | utils:df_to_csv:311 - Save DataFrame: /home/sebaxtian/Workspaces/Tangara/tangara-evaluation/src/data/2_features/temp_correlation.csv

In [12]:
# Save Temperature Data Frame Sensors into CSV file
df_to_csv(df_temp_raw, "temp_raw.csv")

2024-07-15 18:49:14.691 | DEBUG    | utils:df_to_csv:311 - Save DataFrame: /home/sebaxtian/Workspaces/Tangara/tangara-evaluation/src/data/0_raw/temp_raw.csv